version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bankdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: .
    command: sh -c "npm run prisma:db:push && npm run prisma:seed:prod && node dist/src/main"
    volumes:
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/bankdb"
      JWT_SECRET: "markbank"
      JWT_EXPIRES_IN: "8h"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata: